title: Carl the Carmeleon
url: "carlthecarmeleon.com"
permalink: /progress/:title
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - _new_post.rb
  - _template.md
  - README.md
